# Generated by Django 6.0.7 on 2026-07-08 10:35

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Type_doc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DocumentsViewed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Topics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='pic/')),
            ],
            options={
                'db_table': 'User1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('topic', models.TextField(max_length=100)),
                ('subtopics', models.TextField(max_length=100)),
                ('uploaded_at', models.DateTimeField()),
                ('document', models.FileField(upload_to='documents/')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'Documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtopic', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='testrrt.topic')),
            ],
            options={
                'db_table': 'SubTopics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.TextField(default='default_topic', max_length=100)),
                ('subtopics', models.TextField(default='default_subtopic', max_length=100)),
                ('document', models.FileField(upload_to='videos/')),
                ('description', models.CharField(max_length=100)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'Video',
                'managed': True,
            },
        ),
    ]
